config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
 :registrations => 'sessions/registrations'
}
  # get 'users/login'

  # get 'users/signup'

  get  'contents/index'
  post 'contents/create', to: 'contents#create', as: :contents_create

  get 'contents/detail'
  post 'contents/create_comment', to: 'contents#create_comment', as: :create_comment
  delete 'contents/delete'

  root 'contents#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :content
  validates  :text      , presence: true
  validates  :user_id   , presence: true
  validates  :content_id, presence: true
end

app/models/content.rb
class Content < ApplicationRecord
  belongs_to :user
  has_many :comments
  validates :image, presence: true
  validates :caption   , presence: true
  mount_uploader :image, ImageUploader 
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :rememberable, :validatable
  has_many :contents
  has_many :comments
  validates :name, presence: true
  validates :email, presence: true
  validates :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    contents_index_path
  end

  protected
    def configure_permitted_parameters
      #strong parametersを設定し、usernameを許可
      devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
      devise_parameter_sanitizer.permit(:sign_in) { |u| u.permit(:name, :email, :password, :password_confirmation) }
    end

  private
    def sign_in_required
      unless user_signed_in?
        flash[:error] = ["ログインしてください"]
        redirect_to new_user_session_url
      end
    end
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  before_action :sign_in_required
  def index
    # N+1問題対策
    @contents = Content.includes(comments: :user)
    @new_content = Content.new
  end

  def create
    @content = Content.new(content_params)
    @content[:user_id] = current_user.id
    if @content.save
      flash[:success] = ["投稿できました"]
      redirect_to action: :index
    else
      flash[:error] = @content.errors.full_messages
      redirect_to action: :index
    end
  end

  def delete
    @content = Content.find_by(params.permit(:id))
    if @content.destroy
      flash[:success] = "正しく削除されました"
      redirect_to action: :index
    else
      flash[:error] = "削除されませんでした"
    end
  end

  def detail
    @content = Content.includes(comments: :user).find_by(id: params[:id])
    #@content = Content.includes(comments_limit: :user).find_by(id: params[:id])
    if @content.nil?
      head 404
    end

    @new_comment = Comment.new
  end

  def create_comment
    @comment = Comment.new(comment_params)
    @comment[:user_id] = current_user.id
    if @comment.save
      flash[:success] = ["投稿しました"]
      redirect_to action: :detail, id: @comment[:content_id]
    else
      flash[:error] = @comment.errors.full_messages
      redirect_to action: :detail, id: @comment[:content_id]
    end
  end

    private
    def content_params
      params.require(:content).permit(:caption, :image)
    end
    def comment_params
      params.require(:comment).permit(:content_id, :text)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def create
    render layout: 'logout-template'
  end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
  def create
    render layout: 'logout-template'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def login
    render layout: 'logout-template'
  end

  def signup
    render layout: 'logout-template'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contents/detail.html.erb
<% flash.each do |message_type, messages| %>
  <div class="alert alert-<%= message_type %> alert-dismissible">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
    <% if messages.respond_to?(:each) %>
      <% messages.each do |message| %> 
        <li><%= message %></li>
      <% end %>
    <% elsif %>
      <%= messages %>
    <% end %>
  </div>
<% end %>

<div class="bg-light album py-5">
  <div class="container">
      <div class="row">
        <div class="offset-2 col-sm-8 mb-5">
          <div class="card box-shadow">
            <%= image_tag @content.image.url, class: "card-img-top" %>
            <div class="card-body">
              <h5 class="card-title"><b><%= @content.user.name %></b></h5>
              <p class="card-text"><%= @content.caption %></p>
              <h5 class="mt-5"><i class="fa fa-comment"></i> <b>コメント</b></h5>
              <% @content.comments.each do |cm| %>
                <div class="mb-3 comment">
                  <h6 class="card-title"><b><%= cm.user.name %></b></h6>
                  <p class="card-text"><%= cm.text %></p>
                </div>
              <% end %>
              <!-- コメント追加フォーム -->
              <%= form_for @new_comment, url: :create_comment do |nc| %>
                <div class="form-group">
                  <div class="input text">
                    <b><i class="fa fa-pencil"></i> <%= nc.label :新規コメント %></b>
                    <%= nc.text_field  :text, class: "form-control" %>
                    <%= nc.hidden_field :content_id, value: @content.id %>
                  </div>
                </div>
                <%= button_tag type: "submit", class: "btn btn-primary" do %>
                  投稿 <i class="fa fa-arrow-up"></i>
                <% end %>
              <% end %>
              <div class="d-flex justify-content-between align-items-center mt-4">
                <div class="btn-group">
                  <%= link_to :Back, {controler: :contents, action: :index}, class: "btn btn-info btn-sm btn-outline-secondary" %>    
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
  </div>
</div>

app/views/contents/index.html.erb
<div class="container post-container">
  <div class="postarea cf">
    <div class="postarea-text">
      <%= form_for @new_content, url: contents_create_path do |nc| %>
        <div class="form-group">
          <div class="input text">
            <i class="fa fa-pencil-square-o"></i> <%= nc.label :キャプション %>
            <%= nc.text_field  :caption, class: "form-control"  %>
          </div>
        </div>
        <div class="form-group">
          <i class="fa fa-upload"></i> <%= nc.label :画像アップロード %>
          <%= nc.file_field  :image, style: "display:block" %>
        </div>
        <%= button_tag type: "submit", class: "btn btn-primary" do %>
          投稿 <i class="fa fa-arrow-down"></i>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

<% flash.each do |message_type, messages| %>
  <div class="alert alert-<%= message_type %> alert-dismissible">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
    <% if messages.respond_to?(:each) %>
      <% messages.each do |message| %> 
        <li><%= message %></li>
      <% end %>
    <% elsif %>
      <%= messages %>
    <% end %>
  </div>
<% end %>

<div class="bg-light album py-5">
  <div class="container">
    <% @contents.each do |content| %>
      <div class="row">
        <div class="offset-2 col-sm-8 mb-5">
          <div class="card box-shadow">
            <%= image_tag content.image.url, class: "card-img-top" %>
            <div class="card-body">
              <h5 class="card-title"><b><%= content.user.name %></b></h5>
              <p class="card-text"><%= content.caption %></p>
              <div class="d-flex justify-content-between align-items-center mb-3">
                <div class="btn-group">
                    <%= link_to :View, {controler: :contents, action: :detail, id: content.id}, class: "btn btn-sm btn-outline-secondary" %>
                    <%= link_to :Delete, {controler: :contents, action: :delete, id: content.id}, method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn btn-sm btn-outline-secondary" %>
                </div>
              </div>
              <h6 class="mt-5"><b><i class="fa fa-comment"></i> コメント</b></h6>
              <% content.comments.first(5).each do |cm| %>
                <div class="mb-3 comment">
                  <h6 class="card-title"><b><%= cm.user.name %></b></h6>
                  <p class="card-text"><%= cm.text %></p>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MomiziUploader</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <% if user_signed_in? %>
    <body>
      <div class="header">
        <h1 class="logo">
          もみじあっぷろ〜だ〜
          <span class="username-header"> <i class="fa fa-user"></i> <%= current_user.name %> </span>
          <%= link_to destroy_user_session_path, method: :delete, data: {confirm: "ログアウトしますか？"} do %>
            <i class="fa fa-sign-out logout"></i> 
          <% end %>
        </h1>
      </div>
  <% elsif %>
    <body class="hold-transition login-page">
      <div class="header">
        <h1 class="login-logo logo">もみじあっぷろ〜だ〜</h1>
      </div>
      <% flash.each do |message_type, messages| %>
        <div class="alert alert-<%= message_type %> alert-dismissible">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
          <% if messages.respond_to?(:each) %>
            <% messages.each do |message| %> 
              <li><%= message %></li>
            <% end %>
          <% elsif %>
            <%= messages %>
          <% end %>
        </div>
      <% end %>
  <% end %>
      <%= yield %>
    </body>
</html>